// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BootcampProject.Web.Models.EntityModels;

public partial class Ingredient
{
    public int Id { get; set; }

    public string Name { get; set; }

    public DateTime Created { get; set; }

    public DateTime LastUpdated { get; set; }

    public bool Archived { get; set; }

    public virtual ICollection<InventoryIngredient> InventoryIngredients { get; set; } = new List<InventoryIngredient>();

    public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; } = new List<RecipeIngredient>();
}