// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BootcampProject.Web.Models.EntityModels;

public partial class InventoryIngredient
{
    public int Id { get; set; }

    public int IngredientId { get; set; }

    public DateTime Created { get; set; }

    public DateTime LastUpdated { get; set; }

    public bool Archived { get; set; }

    public virtual Ingredient Ingredient { get; set; }
}