// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BootcampProject.Web.Models.EntityModels;

public partial class Recipe
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Instructions { get; set; }

    public int? Rating { get; set; }

    public string Source { get; set; }

    public DateTime Created { get; set; }

    public DateTime LastUpdated { get; set; }

    public bool Archived { get; set; }

    public virtual ICollection<RecipeIngredient> RecipeIngredients { get; set; } = new List<RecipeIngredient>();
}